- hosts: masterdns
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: Disable Swap
      shell: swapoff -a

    - name: Disable Firewall
      shell: systemctl stop firewalld

    - name: Start docker Service
      shell: systemctl start docker.service

    - name: Enable docker Service
      shell: systemctl enable docker.service

    - name: join cluster
      shell: "{{ hostvars['masterdns'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt